// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ULMWrwr7K4QW-iqhAulxetubycLLH-4',
    appId: '1:601906912322:web:72b5d03f9d7b994260e1db',
    messagingSenderId: '601906912322',
    projectId: 'final-gym-app',
    authDomain: 'final-gym-app.firebaseapp.com',
    storageBucket: 'final-gym-app.appspot.com',
    measurementId: 'G-3V8MMQQ80G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhfO8pXxGS69XGR9gqM-epvstefzeuDQ',
    appId: '1:601906912322:android:c211417027023ad860e1db',
    messagingSenderId: '601906912322',
    projectId: 'final-gym-app',
    storageBucket: 'final-gym-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZIDndkFYNlbZH7Xi5mJRNfNlnfJrtEI',
    appId: '1:601906912322:ios:dd3d976ad08ec21760e1db',
    messagingSenderId: '601906912322',
    projectId: 'final-gym-app',
    storageBucket: 'final-gym-app.appspot.com',
    iosBundleId: 'com.example.gymAppFinished',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHZIDndkFYNlbZH7Xi5mJRNfNlnfJrtEI',
    appId: '1:601906912322:ios:dd3d976ad08ec21760e1db',
    messagingSenderId: '601906912322',
    projectId: 'final-gym-app',
    storageBucket: 'final-gym-app.appspot.com',
    iosBundleId: 'com.example.gymAppFinished',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ULMWrwr7K4QW-iqhAulxetubycLLH-4',
    appId: '1:601906912322:web:942f3bb7fc52b99c60e1db',
    messagingSenderId: '601906912322',
    projectId: 'final-gym-app',
    authDomain: 'final-gym-app.firebaseapp.com',
    storageBucket: 'final-gym-app.appspot.com',
    measurementId: 'G-YXBL695Z44',
  );
}
